services:
  frontend:
    volumes:
      - ./frontend/chatbot:/app
    build:
      context: ./frontend/chatbot
      dockerfile: Dockerfile
    ports:
      - 5173:5173
  
  backend:
    volumes:
      - ./backend:/app
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
  
  cache:
    image: redis:7.2
    ports:
      - 6379:6379