services:
  frontend:
    volumes:
      - ./frontend/chatbot:/app
      # - /app/node_modules
    build:
      context: ./frontend/chatbot
      dockerfile: Dockerfile
    ports:
      - 5173:5173

  backend:
    # volumes:
    #   - ./backend:/app
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 8013:8013
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}

  database:
    image: postgres:18.0
    ports:
      - 5432:5432

  vectordb:
    image: qdrant/qdrant:v1.15
    ports:
      - 6333:6333
      - 6334:6334
